### ISSUE TITLE
Logs are improperly formatted when using structured logging

### ISSUE THREAD

**Issue by TAGC** [Stravaig-Projects/Stravaig.Extensions.Configuration.Diagnostics#43]
The logs aren't properly formatted when using a structured logging sink with Serilog. For example, this is what the logs look like on Seq:

![image](https://user-images.githubusercontent.com/1588951/101767498-2dc47d00-3adc-11eb-89b7-2e7477364d19.png)

I think this is because the `ILogger` methods aren't being used correctly, like here:

https://github.com/Stravaig-Projects/Stravaig.Extensions.Configuration.Diagnostics/blob/12f4a6be97b18b8c084f9bb21e42ead6bdb0c611/src/Stravaig.Extensions.Configuration.Diagnostics/ConfigurationRootProviderNameExtensions.cs#L56-L59

To support structured logging, the arguments passed to the logging methods should be a message template (a constant string with placeholders) followed by the objects to fill the template. So it should be something like:

```cs
logger.Log(
    level,
    "The following configuration providers were registered: {Providers}",
    Environment.NewLine + string.Join(Environment.NewLine, providerNames));
```

There's further documentation about that [here.](https://docs.microsoft.com/en-us/dotnet/core/extensions/logging#log-message-template)

**Comment by colinangusmackay** [comment]
It looks like more the new lines are not being rendered correctly. Dumping all the values into a `{providers}` parameter would still have the same issue, wouldn't it? It also has the problem that `{Providers}` element contains numerous items formatted into one string.

Would something like the way the connection strings are logged be more useful?
https://github.com/Stravaig-Projects/Stravaig.Extensions.Configuration.Diagnostics/blob/12f4a6be97b18b8c084f9bb21e42ead6bdb0c611/src/Stravaig.Extensions.Configuration.Diagnostics/ConnectionStringExtensions.cs#L277

**Comment by TAGC** [comment]
> Dumping all the values into a {providers} parameter would still have the same issue, wouldn't it

In the main log text it would, but Seq renders newlines properly for the property itself when you expand the event:

![image](https://user-images.githubusercontent.com/1588951/101807520-1ce02f80-3b0d-11eb-8c35-10a356f741d3.png)

I'm not sure how other structured logging sinks would handle it.

> Would something like the way the connection strings are logged be more useful?

That might be a good idea. At least in Seq's case, it would mean that these event payloads would contain an arbitrary set of properties that could change over time, but that might not be a problem.

I might play around with this if I have time to see what works best.

**Comment by colinangusmackay** [comment]
@TAGC I've added the In Progress label as I see you've forked this and have made a good start on a solution.
